let productsp = [
    {
        id: 1,
        name: "Orégano Orgánico",
        brand: "Brand Name",
        url: "/shop/product/oregano-organico",
        img: "/oregano_min.png",
        price: 100,
    },
    {
        id: 2,
        name: "Cúrcuma",
        brand: "Brand Name",
        url: "/shop/product/curcuma",
        img: "/curcuma_peruana.jpg",
        price: 100,
    },
    {
        id: 3,
        name: "Aceitunas",
        brand: "Brand Name",
        url: "/shop/product/aceitunas-peruanas",
        img: "/aceitunas_peruanas.jpg",
        price: 100,
    },
    {
        id: 4,
        name: "Hongo Deshidratado",
        brand: "Brand Name",
        url: "/shop/product/hongo-deshidratado",
        img: "/hongo_deshidratado_min.jpg",
        price: 100,
    },
    {
        id: 5,
        name: "Café Orgánico",
        brand: "Brand Name",
        url: "/shop/product/cafe-peruano",
        img: "/cafe_peruano.jpg",
        price: 100,
    },
    {
        id: 6,
        name: "Orégano Orgánico",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 7,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 8,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
    {
        id: 1,
        name: "Product Number 1",
        brand: "Brand Name",
        url: "products-number-1",
        img: "/",
        price: 100,
    },
]

export default productsp